version: '3.9'


services:
    postgres:
      container_name: LLM_postgres_container
      image: postgres
      restart: "no"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: db
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
        interval: 2s
        timeout: 1s
        retries: 2

    python-app:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - ./src/deneme.py:/app/src/deneme.py
        - ./src/postgres_login.py:/app/src/postgres_login.py
      command:
        ["sh","-c", "python /app/src/deneme.py && python /app/src/postgres_login.py"]
      environment:
        user: root
        password: root
        host: postgres
      restart: "no"